In [1]:
# ============================================================
# PHASE 6 — FINAL CONSOLIDATION AND THESIS-READY TABLES
# ============================================================

import warnings
from pathlib import Path

import numpy as np
import pandas as pd

warnings.filterwarnings("ignore")

pd.set_option("display.max_columns", 200)
pd.set_option("display.max_colwidth", 250)

# ============================================================
# PATHS
# ============================================================

import os
from pathlib import Path
import pandas as pd
from google.colab import drive

try:
    drive.mount('/content/drive')
except ValueError:
    print("Drive đã được kết nối từ trước.")

PROJECT_DIR = Path("/content/drive/MyDrive/Project_Protein")

# Existing result folders
PHASE4_RESULT_DIR = PROJECT_DIR / "model" / "phase4_biological_validation_preparation" / "results"
PHASE4_1_RESULT_DIR = PROJECT_DIR / "model" / "phase4_1_biological_validation_enrichment" / "results"
PHASE5_RESULT_DIR = PROJECT_DIR / "model" / "phase5_dnabert2_genomic_foundation" / "results"
PHASE5_4B_RESULT_DIR = PROJECT_DIR / "model" / "phase5_4B_dnabert2_biological_quick_validation" / "results"

# Final Phase 6 output
PHASE6_DIR = PROJECT_DIR / "model" / "phase6_final_consolidation"
CSV_DIR = PHASE6_DIR / "csv"
EXCEL_DIR = PHASE6_DIR / "excel"
MD_DIR = PHASE6_DIR / "markdown"
REPORT_DIR = PHASE6_DIR / "reports"

for folder in [PHASE6_DIR, CSV_DIR, EXCEL_DIR, MD_DIR, REPORT_DIR]:
    folder.mkdir(parents=True, exist_ok=True)

print("Phase 6 output:", PHASE6_DIR)

Mounted at /content/drive
Phase 6 output: /content/drive/MyDrive/Project_Protein/model/phase6_final_consolidation

In [2]:
# ============================================================
# HELPER FUNCTIONS
# ============================================================

def read_csv_if_exists(path, required=True):
    path = Path(path)
    if path.exists():
        print("Loaded:", path)
        return pd.read_csv(path)

    msg = f"Missing file: {path}"
    if required:
        raise FileNotFoundError(msg)

    print("Warning:", msg)
    return pd.DataFrame()


def round_numeric_columns(df, digits=4):
    df = df.copy()
    for col in df.columns:
        if pd.api.types.is_float_dtype(df[col]):
            df[col] = df[col].round(digits)
    return df


def save_csv_md(df, name, index=False):
    csv_path = CSV_DIR / f"{name}.csv"
    md_path = MD_DIR / f"{name}.md"

    df.to_csv(csv_path, index=index)

    with open(md_path, "w") as f:
        f.write(df.to_markdown(index=index))

    print("Saved CSV:", csv_path)
    print("Saved MD:", md_path)

    return csv_path, md_path


def clean_text_list(x):
    if pd.isna(x):
        return ""
    return str(x).replace(";", "; ")

In [3]:
# ============================================================
# LOAD SOURCE TABLES
# ============================================================

# Phase 4 old master comparison
phase4_master_path = PHASE4_RESULT_DIR / "phase4_0A_final_master_comparison_table.csv"
phase4_master_df = read_csv_if_exists(phase4_master_path)

# Phase 4.1 biological validation
phase4_enrichment_summary_path = PHASE4_1_RESULT_DIR / "phase4_1_enrichment_summary_by_gene_list.csv"
phase4_top50_support_path = PHASE4_1_RESULT_DIR / "phase4_1_top50_curated_support_summary.csv"
phase4_curated_overlap_path = PHASE4_1_RESULT_DIR / "phase4_1_curated_t2d_gene_set_overlap.csv"

phase4_enrichment_summary_df = read_csv_if_exists(phase4_enrichment_summary_path)
phase4_top50_support_df = read_csv_if_exists(phase4_top50_support_path)
phase4_curated_overlap_df = read_csv_if_exists(phase4_curated_overlap_path)

# Phase 5 master comparison
phase5_master_path = PHASE5_RESULT_DIR / "phase5_4_master_comparison_with_dnabert2.csv"
phase5_master_df = read_csv_if_exists(phase5_master_path)

# Phase 5.4B quick validation
phase5_vs_phase3_metric_path = PHASE5_4B_RESULT_DIR / "phase5_4B_phase5_vs_phase3_metric_delta.csv"
phase5_bio_comparison_path = PHASE5_4B_RESULT_DIR / "phase5_4B_phase5_vs_phase3_biological_validation_comparison.csv"
phase5_top50_overlap_path = PHASE5_4B_RESULT_DIR / "phase5_4B_top50_overlap_phase5_vs_phase3.csv"
phase5_error_group_path = PHASE5_4B_RESULT_DIR / "phase5_4B_phase5_vs_phase3_error_group_summary.csv"
phase5_enrichment_summary_path = PHASE5_4B_RESULT_DIR / "phase5_4B_enrichment_summary_by_gene_list.csv"
phase5_top50_support_path = PHASE5_4B_RESULT_DIR / "phase5_4B_phase5_top50_curated_support_summary.csv"
phase5_curated_overlap_path = PHASE5_4B_RESULT_DIR / "phase5_4B_curated_t2d_gene_set_overlap.csv"

phase5_vs_phase3_metric_df = read_csv_if_exists(phase5_vs_phase3_metric_path)
phase5_bio_comparison_df = read_csv_if_exists(phase5_bio_comparison_path)
phase5_top50_overlap_df = read_csv_if_exists(phase5_top50_overlap_path)
phase5_error_group_df = read_csv_if_exists(phase5_error_group_path)
phase5_enrichment_summary_df = read_csv_if_exists(phase5_enrichment_summary_path)
phase5_top50_support_df = read_csv_if_exists(phase5_top50_support_path)
phase5_curated_overlap_df = read_csv_if_exists(phase5_curated_overlap_path)

print("All source tables loaded.")

Loaded: /content/drive/MyDrive/Project_Protein/model/phase4_biological_validation_preparation/results/phase4_0A_final_master_comparison_table.csv
Loaded: /content/drive/MyDrive/Project_Protein/model/phase4_1_biological_validation_enrichment/results/phase4_1_enrichment_summary_by_gene_list.csv
Loaded: /content/drive/MyDrive/Project_Protein/model/phase4_1_biological_validation_enrichment/results/phase4_1_top50_curated_support_summary.csv
Loaded: /content/drive/MyDrive/Project_Protein/model/phase4_1_biological_validation_enrichment/results/phase4_1_curated_t2d_gene_set_overlap.csv
Loaded: /content/drive/MyDrive/Project_Protein/model/phase5_dnabert2_genomic_foundation/results/phase5_4_master_comparison_with_dnabert2.csv
Loaded: /content/drive/MyDrive/Project_Protein/model/phase5_4B_dnabert2_biological_quick_validation/results/phase5_4B_phase5_vs_phase3_metric_delta.csv
Loaded: /content/drive/MyDrive/Project_Protein/model/phase5_4B_dnabert2_biological_quick_validation/results/phase5_4B_phase5_vs_phase3_biological_validation_comparison.csv
Loaded: /content/drive/MyDrive/Project_Protein/model/phase5_4B_dnabert2_biological_quick_validation/results/phase5_4B_top50_overlap_phase5_vs_phase3.csv
Loaded: /content/drive/MyDrive/Project_Protein/model/phase5_4B_dnabert2_biological_quick_validation/results/phase5_4B_phase5_vs_phase3_error_group_summary.csv
Loaded: /content/drive/MyDrive/Project_Protein/model/phase5_4B_dnabert2_biological_quick_validation/results/phase5_4B_enrichment_summary_by_gene_list.csv
Loaded: /content/drive/MyDrive/Project_Protein/model/phase5_4B_dnabert2_biological_quick_validation/results/phase5_4B_phase5_top50_curated_support_summary.csv
Loaded: /content/drive/MyDrive/Project_Protein/model/phase5_4B_dnabert2_biological_quick_validation/results/phase5_4B_curated_t2d_gene_set_overlap.csv
All source tables loaded.

In [4]:
# ============================================================
# TABLE 1 — FINAL MASTER COMPARISON TABLE V2
# ============================================================

# Use Phase 5 master as base because it already includes Phase 1-5 key models.
final_master_v2_df = phase5_master_df.copy()

# Standardize columns if needed
expected_cols = [
    "phase",
    "branch",
    "representation",
    "embedding_policy",
    "feature_type",
    "model",
    "test_roc_auc",
    "test_pr_auc",
    "test_f1",
    "test_mcc",
    "note"
]

final_master_v2_df = final_master_v2_df[
    [col for col in expected_cols if col in final_master_v2_df.columns]
].copy()

final_master_v2_df = final_master_v2_df.sort_values(
    by=["test_roc_auc", "test_pr_auc", "test_mcc"],
    ascending=False
).reset_index(drop=True)

final_master_v2_df.insert(
    0,
    "rank_by_roc_auc",
    np.arange(1, len(final_master_v2_df) + 1)
)

# Add role column
def assign_model_role(row):
    phase = str(row.get("phase", ""))
    representation = str(row.get("representation", ""))

    if phase == "3.1" and "K3" in representation:
        return "official_biologically_validated_model"

    if phase == "5.3" and "DNABERT" in representation:
        return "best_roc_auc_extension_model"

    if phase == "3.1" and "Protein" in str(row.get("branch", "")):
        return "best_protein_only_shared_split_model"

    if phase == "5.2":
        return "genomic_foundation_extension"

    if phase == "2.1":
        return "handcrafted_genomic_baseline"

    if phase == "1.2E":
        return "protein_foundation_baseline"

    return "supporting_baseline"

final_master_v2_df["final_role"] = final_master_v2_df.apply(assign_model_role, axis=1)

final_master_v2_df = round_numeric_columns(final_master_v2_df, 4)

display(final_master_v2_df)

save_csv_md(
    final_master_v2_df,
    "table1_final_master_comparison_v2"
)

,rank_by_roc_auc,phase,branch,representation,embedding_policy,feature_type,model,test_roc_auc,test_pr_auc,test_f1,test_mcc,note,final_role
0,1,5.3,Multimodal,ProtBERT-SW + DNABERT-2,early_fusion,protein foundation embedding + genomic foundation embedding,SVM RBF,0.7568,0.7447,0.6616,0.3435,Multimodal foundation-model extension,best_roc_auc_extension_model
1,2,3.1,Multimodal,ProtBERT-SW + K3/K4/Basic,early_fusion,protein embedding + handcrafted genomic,SVM RBF,0.7290,0.7573,0.6590,0.3438,Official multimodal model before DNABERT-2,official_biologically_validated_model
2,3,3.1,Protein shared split,ProtBERT-SW,shared split,protein foundation embedding,SVM RBF,0.7274,0.7433,0.6667,0.3215,Protein-only on Phase 3 shared split,best_protein_only_shared_split_model
3,4,5.2,Genomic regulatory,DNABERT-2,sliding_window_2048_stride_1024,genomic foundation embedding,Random Forest,0.6833,0.6838,0.5478,0.2425,DNABERT-2 genomic-only extension,genomic_foundation_extension
4,5,2.1,Genomic regulatory,K3 + K4 + Basic,handcrafted,genomic handcrafted regulatory features,Random Forest,0.6496,0.6327,0.6406,0.2557,Official handcrafted genomic model,handcrafted_genomic_baseline
5,6,1.2E,Protein,ProtBERT,sliding_window_1022_stride_1022,protein foundation embedding,Logistic Regression,0.6487,0.6551,0.5896,0.1941,Best protein model before shared split,protein_foundation_baseline

Saved CSV: /content/drive/MyDrive/Project_Protein/model/phase6_final_consolidation/csv/table1_final_master_comparison_v2.csv
Saved MD: /content/drive/MyDrive/Project_Protein/model/phase6_final_consolidation/markdown/table1_final_master_comparison_v2.md

(PosixPath('/content/drive/MyDrive/Project_Protein/model/phase6_final_consolidation/csv/table1_final_master_comparison_v2.csv'),
 PosixPath('/content/drive/MyDrive/Project_Protein/model/phase6_final_consolidation/markdown/table1_final_master_comparison_v2.md'))

In [5]:
# ============================================================
# TABLE 2 — FINAL DECISION TABLE
# ============================================================

# From Phase 5.4B metric delta
decision_metrics_df = phase5_vs_phase3_metric_df.copy()

# From Phase 5.4B biological comparison
bio_df = phase5_bio_comparison_df.copy()

# Normalize model labels to merge manually
phase3_metric_row = decision_metrics_df[
    decision_metrics_df["model_name"].str.contains("Phase 3.1", case=False, na=False)
].iloc[0]

phase5_metric_row = decision_metrics_df[
    decision_metrics_df["model_name"].str.contains("Phase 5.3", case=False, na=False)
].iloc[0]

phase3_bio_row = bio_df[
    bio_df["model"].str.contains("Phase 3.1", case=False, na=False)
].iloc[0]

phase5_bio_row = bio_df[
    bio_df["model"].str.contains("Phase 5.3", case=False, na=False)
].iloc[0]

decision_records = [
    {
        "model_role": "Official biologically validated model",
        "phase": "3.1",
        "model": "Combined ProtBERT-SW + K3/K4/Basic SVM RBF",
        "genomic_representation": "Handcrafted K3/K4/Basic TSS-proximal regulatory features",
        "test_roc_auc": phase3_metric_row["roc_auc"],
        "test_pr_auc": phase3_metric_row["pr_auc"],
        "test_f1": phase3_metric_row["f1"],
        "test_mcc": phase3_metric_row["mcc"],
        "top50_curated_support": f"{int(phase3_bio_row['top50_curated_supported_n'])}/50 ({phase3_bio_row['top50_curated_supported_pct']:.1f}%)",
        "top50_significant_terms": int(phase3_bio_row["top50_significant_terms"]),
        "top50_t2d_relevant_terms": int(phase3_bio_row["top50_t2d_relevant_terms"]),
        "top_t2d_relevant_term": phase3_bio_row["top_t2d_relevant_term"],
        "decision": "Retain as main biologically validated model"
    },
    {
        "model_role": "Best ROC-AUC extension model",
        "phase": "5.3",
        "model": "Combined ProtBERT-SW + DNABERT-2 SVM RBF",
        "genomic_representation": "DNABERT-2 genomic foundation embedding",
        "test_roc_auc": phase5_metric_row["roc_auc"],
        "test_pr_auc": phase5_metric_row["pr_auc"],
        "test_f1": phase5_metric_row["f1"],
        "test_mcc": phase5_metric_row["mcc"],
        "top50_curated_support": f"{int(phase5_bio_row['top50_curated_supported_n'])}/50 ({phase5_bio_row['top50_curated_supported_pct']:.1f}%)",
        "top50_significant_terms": int(phase5_bio_row["top50_significant_terms"]),
        "top50_t2d_relevant_terms": int(phase5_bio_row["top50_t2d_relevant_terms"]),
        "top_t2d_relevant_term": phase5_bio_row["top_t2d_relevant_term"],
        "decision": "Report as DNABERT-2 extension with best ROC-AUC"
    }
]

final_decision_df = pd.DataFrame(decision_records)
final_decision_df = round_numeric_columns(final_decision_df, 4)

display(final_decision_df)

save_csv_md(
    final_decision_df,
    "table2_final_model_decision_phase3_vs_phase5"
)

,model_role,phase,model,genomic_representation,test_roc_auc,test_pr_auc,test_f1,test_mcc,top50_curated_support,top50_significant_terms,top50_t2d_relevant_terms,top_t2d_relevant_term,decision
0,Official biologically validated model,3.1,Combined ProtBERT-SW + K3/K4/Basic SVM RBF,Handcrafted K3/K4/Basic TSS-proximal regulatory features,0.7290,0.7573,0.6590,0.3438,15/50 (30.0%),102,41,Oxidative phosphorylation,Retain as main biologically validated model
1,Best ROC-AUC extension model,5.3,Combined ProtBERT-SW + DNABERT-2 SVM RBF,DNABERT-2 genomic foundation embedding,0.7568,0.7447,0.6642,0.3433,10/50 (20.0%),43,16,"DNA-binding transcription activator activity, RNA polymerase II-specific",Report as DNABERT-2 extension with best ROC-AUC

Saved CSV: /content/drive/MyDrive/Project_Protein/model/phase6_final_consolidation/csv/table2_final_model_decision_phase3_vs_phase5.csv
Saved MD: /content/drive/MyDrive/Project_Protein/model/phase6_final_consolidation/markdown/table2_final_model_decision_phase3_vs_phase5.md

(PosixPath('/content/drive/MyDrive/Project_Protein/model/phase6_final_consolidation/csv/table2_final_model_decision_phase3_vs_phase5.csv'),
 PosixPath('/content/drive/MyDrive/Project_Protein/model/phase6_final_consolidation/markdown/table2_final_model_decision_phase3_vs_phase5.md'))

In [6]:
# ============================================================
# TABLE 3 — METRIC DELTA SUMMARY
# ============================================================

phase5_delta_row = phase5_metric_row.copy()

metric_delta_summary_df = pd.DataFrame([
    {
        "comparison": "Phase 5.3 DNABERT-2 extension minus Phase 3.1 handcrafted-genomic multimodal",
        "delta_roc_auc": phase5_delta_row["delta_vs_phase3_roc_auc"],
        "delta_pr_auc": phase5_delta_row["delta_vs_phase3_pr_auc"],
        "delta_f1": phase5_delta_row["delta_vs_phase3_f1"],
        "delta_mcc": phase5_delta_row["delta_vs_phase3_mcc"],
        "interpretation": (
            "DNABERT-2 improves ROC-AUC and slightly improves F1, "
            "but the Phase 3.1 handcrafted-genomic multimodal model remains slightly better in PR-AUC and MCC."
        )
    }
])

metric_delta_summary_df = round_numeric_columns(metric_delta_summary_df, 4)

display(metric_delta_summary_df)

save_csv_md(
    metric_delta_summary_df,
    "table3_metric_delta_summary"
)

,comparison,delta_roc_auc,delta_pr_auc,delta_f1,delta_mcc,interpretation
0,Phase 5.3 DNABERT-2 extension minus Phase 3.1 handcrafted-genomic multimodal,0.0278,-0.0126,0.0052,-0.0005,"DNABERT-2 improves ROC-AUC and slightly improves F1, but the Phase 3.1 handcrafted-genomic multimodal model remains slightly better in PR-AUC and MCC."

Saved CSV: /content/drive/MyDrive/Project_Protein/model/phase6_final_consolidation/csv/table3_metric_delta_summary.csv
Saved MD: /content/drive/MyDrive/Project_Protein/model/phase6_final_consolidation/markdown/table3_metric_delta_summary.md

(PosixPath('/content/drive/MyDrive/Project_Protein/model/phase6_final_consolidation/csv/table3_metric_delta_summary.csv'),
 PosixPath('/content/drive/MyDrive/Project_Protein/model/phase6_final_consolidation/markdown/table3_metric_delta_summary.md'))

In [7]:
# ============================================================
# TABLE 4 — BIOLOGICAL VALIDATION COMPARISON
# ============================================================

bio_validation_comparison_df = phase5_bio_comparison_df.copy()

bio_validation_comparison_df = bio_validation_comparison_df.rename(columns={
    "model": "model",
    "top50_curated_supported_n": "top50_curated_supported_n",
    "top50_curated_supported_pct": "top50_curated_supported_pct",
    "top50_significant_terms": "top50_significant_terms",
    "top50_t2d_relevant_terms": "top50_t2d_relevant_terms",
    "top_t2d_relevant_term": "top_t2d_relevant_term"
})

bio_validation_comparison_df = round_numeric_columns(bio_validation_comparison_df, 2)

display(bio_validation_comparison_df)

save_csv_md(
    bio_validation_comparison_df,
    "table4_biological_validation_comparison"
)

,model,top50_curated_supported_n,top50_curated_supported_pct,top50_significant_terms,top50_t2d_relevant_terms,top_t2d_relevant_term
0,Phase 3.1 Combined ProtBERT-SW + K3/K4/Basic,15,30.0,102,41,Oxidative phosphorylation
1,Phase 5.3 Combined ProtBERT-SW + DNABERT-2,10,20.0,43,16,"DNA-binding transcription activator activity, RNA polymerase II-specific"

Saved CSV: /content/drive/MyDrive/Project_Protein/model/phase6_final_consolidation/csv/table4_biological_validation_comparison.csv
Saved MD: /content/drive/MyDrive/Project_Protein/model/phase6_final_consolidation/markdown/table4_biological_validation_comparison.md

(PosixPath('/content/drive/MyDrive/Project_Protein/model/phase6_final_consolidation/csv/table4_biological_validation_comparison.csv'),
 PosixPath('/content/drive/MyDrive/Project_Protein/model/phase6_final_consolidation/markdown/table4_biological_validation_comparison.md'))

In [8]:
# ============================================================
# TABLE 5 — TOP 50 STABILITY BETWEEN PHASE 3 AND PHASE 5
# ============================================================

top50_stability_df = phase5_top50_overlap_df.copy()

# Clean long gene columns for readability
for col in ["shared_top50_genes", "phase5_new_only_top50_genes", "old_only_top50_genes"]:
    if col in top50_stability_df.columns:
        top50_stability_df[col] = top50_stability_df[col].apply(clean_text_list)

top50_stability_df = round_numeric_columns(top50_stability_df, 4)

display(top50_stability_df)

save_csv_md(
    top50_stability_df,
    "table5_top50_stability_phase3_vs_phase5"
)

,old_phase3_top50_n,phase5_top50_n,shared_top50_n,phase5_new_only_top50_n,old_only_top50_n,jaccard_overlap,shared_top50_genes,phase5_new_only_top50_genes,old_only_top50_genes
0,50,50,39,11,11,0.6393,ACADS; ADCY9; ADRB1; ATP1A2; BCL11B; CACNA1D; CCDC6; CPEB3; DACH1; DNMT3A; DYRK2; ETV1; FAXC; FOXN3; GAD1; GALNT10; HHEX; IGF2BP2; INSR; ISL1; L3MBTL3; MEIS1; MRC2; NDUFB2; NDUFV1; NEUROD1; NFAT5; NT5C2; PAXIP1; PDX1; PPP2R2C; PRDM5; PTPRM; RHBDL...,CHRNA1; DDC; EBF2; GALNT3; GLRA1; IGSF21; MAGI1; NCALD; NSD3; PARP8; TUBB4A,DPP4; EIF4E2; GATD3; GRM7; HMG20A; MGAM; NDUFA7; NDUFB1; NDUFB3; RALY; SLC5A1

Saved CSV: /content/drive/MyDrive/Project_Protein/model/phase6_final_consolidation/csv/table5_top50_stability_phase3_vs_phase5.csv
Saved MD: /content/drive/MyDrive/Project_Protein/model/phase6_final_consolidation/markdown/table5_top50_stability_phase3_vs_phase5.md

(PosixPath('/content/drive/MyDrive/Project_Protein/model/phase6_final_consolidation/csv/table5_top50_stability_phase3_vs_phase5.csv'),
 PosixPath('/content/drive/MyDrive/Project_Protein/model/phase6_final_consolidation/markdown/table5_top50_stability_phase3_vs_phase5.md'))

In [9]:
# ============================================================
# TABLE 6 — ERROR EXCHANGE PHASE 3 VS PHASE 5
# ============================================================

error_exchange_df = phase5_error_group_df.copy()

error_exchange_df = error_exchange_df.rename(columns={
    "error_group": "phase5_vs_phase3_error_group",
    "n_genes": "n_genes",
    "percentage": "percentage"
})

error_exchange_df = round_numeric_columns(error_exchange_df, 2)

display(error_exchange_df)

save_csv_md(
    error_exchange_df,
    "table6_error_exchange_phase3_vs_phase5"
)

  phase5_vs_phase3_error_group  n_genes  percentage
0                 both_correct      168       61.99
1                   both_wrong       75       27.68
2  phase3_correct_phase5_wrong       14        5.17
3  phase5_correct_phase3_wrong       14        5.17

Saved CSV: /content/drive/MyDrive/Project_Protein/model/phase6_final_consolidation/csv/table6_error_exchange_phase3_vs_phase5.csv
Saved MD: /content/drive/MyDrive/Project_Protein/model/phase6_final_consolidation/markdown/table6_error_exchange_phase3_vs_phase5.md

(PosixPath('/content/drive/MyDrive/Project_Protein/model/phase6_final_consolidation/csv/table6_error_exchange_phase3_vs_phase5.csv'),
 PosixPath('/content/drive/MyDrive/Project_Protein/model/phase6_final_consolidation/markdown/table6_error_exchange_phase3_vs_phase5.md'))

In [10]:
# ============================================================
# TABLE 7 — FINAL CLAIMS AND EVIDENCE
# ============================================================

final_claims_records = [
    {
        "claim_id": "C1",
        "claim": "Protein foundation embeddings provide the dominant predictive signal.",
        "evidence": (
            "ProtBERT-SW protein-only model on shared split achieved ROC-AUC 0.7274 and PR-AUC 0.7433, "
            "close to the multimodal model."
        ),
        "support_level": "strong"
    },
    {
        "claim_id": "C2",
        "claim": "Handcrafted TSS-proximal genomic features provide complementary signal.",
        "evidence": (
            "Adding K3/K4/Basic genomic features to ProtBERT-SW improved PR-AUC to 0.7573 and MCC to 0.3438, "
            "and produced the strongest biological validation results."
        ),
        "support_level": "strong"
    },
    {
        "claim_id": "C3",
        "claim": "DNABERT-2 genomic foundation embeddings improve global ranking separation.",
        "evidence": (
            "Combined ProtBERT-SW + DNABERT-2 achieved the highest ROC-AUC in the project: 0.7568, "
            "improving over Phase 3.1 by +0.0278."
        ),
        "support_level": "strong"
    },
    {
        "claim_id": "C4",
        "claim": "DNABERT-2 does not fully replace the handcrafted genomic branch in the current study.",
        "evidence": (
            "Phase 3.1 retained higher PR-AUC and MCC and stronger top-50 biological validation "
            "than Phase 5.3."
        ),
        "support_level": "moderate_to_strong"
    },
    {
        "claim_id": "C5",
        "claim": "The final framework is biologically plausible.",
        "evidence": (
            "Top true positives and top 50 Phase 3 predictions were enriched for oxidative phosphorylation, "
            "respiratory chain complex I, insulin resistance, type II diabetes mellitus, insulin secretion, "
            "and pancreas development."
        ),
        "support_level": "strong"
    }
]

final_claims_df = pd.DataFrame(final_claims_records)

display(final_claims_df)

save_csv_md(
    final_claims_df,
    "table7_final_claims_and_evidence"
)

,claim_id,claim,evidence,support_level
0,C1,Protein foundation embeddings provide the dominant predictive signal.,"ProtBERT-SW protein-only model on shared split achieved ROC-AUC 0.7274 and PR-AUC 0.7433, close to the multimodal model.",strong
1,C2,Handcrafted TSS-proximal genomic features provide complementary signal.,"Adding K3/K4/Basic genomic features to ProtBERT-SW improved PR-AUC to 0.7573 and MCC to 0.3438, and produced the strongest biological validation results.",strong
2,C3,DNABERT-2 genomic foundation embeddings improve global ranking separation.,"Combined ProtBERT-SW + DNABERT-2 achieved the highest ROC-AUC in the project: 0.7568, improving over Phase 3.1 by +0.0278.",strong
3,C4,DNABERT-2 does not fully replace the handcrafted genomic branch in the current study.,Phase 3.1 retained higher PR-AUC and MCC and stronger top-50 biological validation than Phase 5.3.,moderate_to_strong
4,C5,The final framework is biologically plausible.,"Top true positives and top 50 Phase 3 predictions were enriched for oxidative phosphorylation, respiratory chain complex I, insulin resistance, type II diabetes mellitus, insulin secretion, and pancreas development.",strong

Saved CSV: /content/drive/MyDrive/Project_Protein/model/phase6_final_consolidation/csv/table7_final_claims_and_evidence.csv
Saved MD: /content/drive/MyDrive/Project_Protein/model/phase6_final_consolidation/markdown/table7_final_claims_and_evidence.md

(PosixPath('/content/drive/MyDrive/Project_Protein/model/phase6_final_consolidation/csv/table7_final_claims_and_evidence.csv'),
 PosixPath('/content/drive/MyDrive/Project_Protein/model/phase6_final_consolidation/markdown/table7_final_claims_and_evidence.md'))

In [11]:
# ============================================================
# TABLE 8 — COMPACT FINAL REPORT SUMMARY
# ============================================================

compact_final_summary_records = [
    {
        "section": "Best biologically validated model",
        "result": "Phase 3.1 Combined ProtBERT-SW + K3/K4/Basic SVM RBF",
        "key_metrics": "ROC-AUC 0.7290; PR-AUC 0.7573; F1 0.6590; MCC 0.3438",
        "interpretation": "Retained as the main official model because it has the strongest biological validation."
    },
    {
        "section": "Best ROC-AUC model",
        "result": "Phase 5.3 Combined ProtBERT-SW + DNABERT-2 SVM RBF",
        "key_metrics": "ROC-AUC 0.7568; PR-AUC 0.7447; F1 0.6642; MCC 0.3433",
        "interpretation": "Reported as the DNABERT-2 extension and best global ranking model."
    },
    {
        "section": "Biological validation",
        "result": "Phase 3.1 top 50 predictions",
        "key_metrics": "102 significant terms; 41 T2D-relevant terms; 15/50 curated support",
        "interpretation": "Shows strongest enrichment and curated T2D-related support."
    },
    {
        "section": "DNABERT-2 extension",
        "result": "Phase 5.3 top 50 predictions",
        "key_metrics": "43 significant terms; 16 T2D-relevant terms; 10/50 curated support",
        "interpretation": "Biologically plausible, but weaker biological validation than Phase 3.1."
    },
    {
        "section": "Final conclusion",
        "result": "Protein embeddings dominate; genomic features complement; DNABERT-2 improves ROC-AUC.",
        "key_metrics": "Phase 5 ROC-AUC gain over Phase 3: +0.0278",
        "interpretation": "Best framed as a biologically plausible multimodal framework with a promising genomic foundation-model extension."
    }
]

compact_final_summary_df = pd.DataFrame(compact_final_summary_records)

display(compact_final_summary_df)

save_csv_md(
    compact_final_summary_df,
    "table8_compact_final_report_summary"
)

,section,result,key_metrics,interpretation
0,Best biologically validated model,Phase 3.1 Combined ProtBERT-SW + K3/K4/Basic SVM RBF,ROC-AUC 0.7290; PR-AUC 0.7573; F1 0.6590; MCC 0.3438,Retained as the main official model because it has the strongest biological validation.
1,Best ROC-AUC model,Phase 5.3 Combined ProtBERT-SW + DNABERT-2 SVM RBF,ROC-AUC 0.7568; PR-AUC 0.7447; F1 0.6642; MCC 0.3433,Reported as the DNABERT-2 extension and best global ranking model.
2,Biological validation,Phase 3.1 top 50 predictions,102 significant terms; 41 T2D-relevant terms; 15/50 curated support,Shows strongest enrichment and curated T2D-related support.
3,DNABERT-2 extension,Phase 5.3 top 50 predictions,43 significant terms; 16 T2D-relevant terms; 10/50 curated support,"Biologically plausible, but weaker biological validation than Phase 3.1."
4,Final conclusion,Protein embeddings dominate; genomic features complement; DNABERT-2 improves ROC-AUC.,Phase 5 ROC-AUC gain over Phase 3: +0.0278,Best framed as a biologically plausible multimodal framework with a promising genomic foundation-model extension.

Saved CSV: /content/drive/MyDrive/Project_Protein/model/phase6_final_consolidation/csv/table8_compact_final_report_summary.csv
Saved MD: /content/drive/MyDrive/Project_Protein/model/phase6_final_consolidation/markdown/table8_compact_final_report_summary.md

(PosixPath('/content/drive/MyDrive/Project_Protein/model/phase6_final_consolidation/csv/table8_compact_final_report_summary.csv'),
 PosixPath('/content/drive/MyDrive/Project_Protein/model/phase6_final_consolidation/markdown/table8_compact_final_report_summary.md'))

In [12]:
# ============================================================
# EXPORT ALL PHASE 6 TABLES TO EXCEL
# ============================================================

excel_path = EXCEL_DIR / "phase6_final_consolidation_tables.xlsx"

tables_to_export = {
    "T1_Master_v2": final_master_v2_df,
    "T2_Final_Decision": final_decision_df,
    "T3_Metric_Delta": metric_delta_summary_df,
    "T4_Bio_Comparison": bio_validation_comparison_df,
    "T5_Top50_Stability": top50_stability_df,
    "T6_Error_Exchange": error_exchange_df,
    "T7_Final_Claims": final_claims_df,
    "T8_Compact_Summary": compact_final_summary_df,
}

with pd.ExcelWriter(excel_path, engine="openpyxl") as writer:
    for sheet_name, df in tables_to_export.items():
        safe_sheet_name = sheet_name[:31]
        df.to_excel(writer, sheet_name=safe_sheet_name, index=False)

print("Saved Excel workbook:", excel_path)

Saved Excel workbook: /content/drive/MyDrive/Project_Protein/model/phase6_final_consolidation/excel/phase6_final_consolidation_tables.xlsx

In [13]:
# ============================================================
# WRITE FINAL UPDATED REPORT SUMMARY
# ============================================================

final_report_text = """
# Final Consolidated Report Summary — Phase 1 to Phase 6

## Final Model Decision

This project evaluated protein sequence representations, genomic regulatory sequence features, multimodal integration, biological validation, and a DNABERT-2 genomic foundation-model extension for Type 2 Diabetes-associated gene/protein prediction.

The final model decision separates two roles:

1. Official biologically validated model
2. Best ROC-AUC extension model

## Official Biologically Validated Model

The official biologically validated model is:

Combined ProtBERT-SW + K3/K4/Basic SVM RBF

This model achieved:

- ROC-AUC: 0.7290
- PR-AUC: 0.7573
- F1: 0.6590
- MCC: 0.3438

It is retained as the main biologically validated model because its top-ranked predictions showed the strongest biological enrichment and curated T2D-related support.

Specifically, the top 50 predictions produced:

- 102 significant enrichment terms
- 41 T2D-relevant enrichment terms
- 15/50 genes with curated T2D-related support

The enriched terms included oxidative phosphorylation, respiratory chain complex I, insulin resistance, type II diabetes mellitus, insulin secretion, and pancreas development.

## Best ROC-AUC Extension Model

The best ROC-AUC model is:

Combined ProtBERT-SW + DNABERT-2 SVM RBF

This model achieved:

- ROC-AUC: 0.7568
- PR-AUC: 0.7447
- F1: 0.6642
- MCC: 0.3433

Compared with the Phase 3.1 handcrafted-genomic multimodal model, the DNABERT-2 extension improved ROC-AUC by +0.0278. This suggests that DNABERT-2 genomic embeddings improve global ranking separation and capture useful regulatory sequence context beyond handcrafted k-mer features.

However, the DNABERT-2 extension did not fully replace the handcrafted genomic branch. The Phase 3.1 model retained higher PR-AUC, slightly higher MCC, and stronger biological validation among top-ranked genes.

## Final Interpretation

Protein foundation embeddings provide the dominant disease-association signal in this project. Genomic regulatory features provide complementary information, especially when integrated with protein embeddings. Handcrafted K3/K4/Basic TSS-proximal features produced the strongest biological validation, while DNABERT-2 embeddings improved ROC-AUC as a genomic foundation-model extension.

Therefore, the final conclusion is:

The proposed framework demonstrates that protein foundation embeddings are highly informative for T2D gene/protein association prediction, while genomic regulatory features add complementary biological context. DNABERT-2 further improves global ranking performance, supporting the value of genomic foundation models, but additional fine-tuning and biological validation are needed before replacing the handcrafted genomic branch as the main biologically validated model.

## Recommended Report Framing

The final report should present:

- Phase 3.1 as the official biologically validated multimodal model.
- Phase 5.3 as the best ROC-AUC DNABERT-2 extension.
- Phase 6 as the final consolidation proving that both handcrafted genomic features and genomic foundation embeddings have value.

## Final Claim

Protein embeddings are the main predictive signal, TSS-proximal genomic features add complementary biological information, and DNABERT-2 provides a promising extension that improves ROC-AUC but requires stronger biological validation and/or fine-tuning for future work.
"""

report_path = REPORT_DIR / "phase6_final_consolidated_report_summary.md"

with open(report_path, "w") as f:
    f.write(final_report_text)

print(final_report_text)
print("Saved report:", report_path)

# Final Consolidated Report Summary — Phase 1 to Phase 6

## Final Model Decision

This project evaluated protein sequence representations, genomic regulatory sequence features, multimodal integration, biological validation, and a DNABERT-2 genomic foundation-model extension for Type 2 Diabetes-associated gene/protein prediction.

The final model decision separates two roles:

1. Official biologically validated model
2. Best ROC-AUC extension model

## Official Biologically Validated Model

The official biologically validated model is:

Combined ProtBERT-SW + K3/K4/Basic SVM RBF

This model achieved:

- ROC-AUC: 0.7290
- PR-AUC: 0.7573
- F1: 0.6590
- MCC: 0.3438

It is retained as the main biologically validated model because its top-ranked predictions showed the strongest biological enrichment and curated T2D-related support.

Specifically, the top 50 predictions produced:

- 102 significant enrichment terms
- 41 T2D-relevant enrichment terms
- 15/50 genes with curated T2D-related support

The enriched terms included oxidative phosphorylation, respiratory chain complex I, insulin resistance, type II diabetes mellitus, insulin secretion, and pancreas development.

## Best ROC-AUC Extension Model

The best ROC-AUC model is:

Combined ProtBERT-SW + DNABERT-2 SVM RBF

This model achieved:

- ROC-AUC: 0.7568
- PR-AUC: 0.7447
- F1: 0.6642
- MCC: 0.3433

Compared with the Phase 3.1 handcrafted-genomic multimodal model, the DNABERT-2 extension improved ROC-AUC by +0.0278. This suggests that DNABERT-2 genomic embeddings improve global ranking separation and capture useful regulatory sequence context beyond handcrafted k-mer features.

However, the DNABERT-2 extension did not fully replace the handcrafted genomic branch. The Phase 3.1 model retained higher PR-AUC, slightly higher MCC, and stronger biological validation among top-ranked genes.

## Final Interpretation

Protein foundation embeddings provide the dominant disease-association signal in this project. Genomic regulatory features provide complementary information, especially when integrated with protein embeddings. Handcrafted K3/K4/Basic TSS-proximal features produced the strongest biological validation, while DNABERT-2 embeddings improved ROC-AUC as a genomic foundation-model extension.

Therefore, the final conclusion is:

The proposed framework demonstrates that protein foundation embeddings are highly informative for T2D gene/protein association prediction, while genomic regulatory features add complementary biological context. DNABERT-2 further improves global ranking performance, supporting the value of genomic foundation models, but additional fine-tuning and biological validation are needed before replacing the handcrafted genomic branch as the main biologically validated model.

## Recommended Report Framing

The final report should present:

- Phase 3.1 as the official biologically validated multimodal model.
- Phase 5.3 as the best ROC-AUC DNABERT-2 extension.
- Phase 6 as the final consolidation proving that both handcrafted genomic features and genomic foundation embeddings have value.

## Final Claim

Protein embeddings are the main predictive signal, TSS-proximal genomic features add complementary biological information, and DNABERT-2 provides a promising extension that improves ROC-AUC but requires stronger biological validation and/or fine-tuning for future work.

Saved report: /content/drive/MyDrive/Project_Protein/model/phase6_final_consolidation/reports/phase6_final_consolidated_report_summary.md

In [14]:
# ============================================================
# LIST OUTPUT FILES
# ============================================================

print("=== CSV FILES ===")
for p in sorted(CSV_DIR.glob("*.csv")):
    print(p)

print("\n=== MARKDOWN FILES ===")
for p in sorted(MD_DIR.glob("*.md")):
    print(p)

print("\n=== EXCEL FILES ===")
for p in sorted(EXCEL_DIR.glob("*.xlsx")):
    print(p)

print("\n=== REPORT FILES ===")
for p in sorted(REPORT_DIR.glob("*.md")):
    print(p)

=== CSV FILES ===
/content/drive/MyDrive/Project_Protein/model/phase6_final_consolidation/csv/table1_final_master_comparison_v2.csv
/content/drive/MyDrive/Project_Protein/model/phase6_final_consolidation/csv/table2_final_model_decision_phase3_vs_phase5.csv
/content/drive/MyDrive/Project_Protein/model/phase6_final_consolidation/csv/table3_metric_delta_summary.csv
/content/drive/MyDrive/Project_Protein/model/phase6_final_consolidation/csv/table4_biological_validation_comparison.csv
/content/drive/MyDrive/Project_Protein/model/phase6_final_consolidation/csv/table5_top50_stability_phase3_vs_phase5.csv
/content/drive/MyDrive/Project_Protein/model/phase6_final_consolidation/csv/table6_error_exchange_phase3_vs_phase5.csv
/content/drive/MyDrive/Project_Protein/model/phase6_final_consolidation/csv/table7_final_claims_and_evidence.csv
/content/drive/MyDrive/Project_Protein/model/phase6_final_consolidation/csv/table8_compact_final_report_summary.csv

=== MARKDOWN FILES ===
/content/drive/MyDrive/Project_Protein/model/phase6_final_consolidation/markdown/table1_final_master_comparison_v2.md
/content/drive/MyDrive/Project_Protein/model/phase6_final_consolidation/markdown/table2_final_model_decision_phase3_vs_phase5.md
/content/drive/MyDrive/Project_Protein/model/phase6_final_consolidation/markdown/table3_metric_delta_summary.md
/content/drive/MyDrive/Project_Protein/model/phase6_final_consolidation/markdown/table4_biological_validation_comparison.md
/content/drive/MyDrive/Project_Protein/model/phase6_final_consolidation/markdown/table5_top50_stability_phase3_vs_phase5.md
/content/drive/MyDrive/Project_Protein/model/phase6_final_consolidation/markdown/table6_error_exchange_phase3_vs_phase5.md
/content/drive/MyDrive/Project_Protein/model/phase6_final_consolidation/markdown/table7_final_claims_and_evidence.md
/content/drive/MyDrive/Project_Protein/model/phase6_final_consolidation/markdown/table8_compact_final_report_summary.md

=== EXCEL FILES ===
/content/drive/MyDrive/Project_Protein/model/phase6_final_consolidation/excel/phase6_final_consolidation_tables.xlsx

=== REPORT FILES ===
/content/drive/MyDrive/Project_Protein/model/phase6_final_consolidation/reports/phase6_final_consolidated_report_summary.md

In [15]:
display(final_master_v2_df)
display(final_decision_df)
display(metric_delta_summary_df)
display(bio_validation_comparison_df)
display(final_claims_df)
display(compact_final_summary_df)

,rank_by_roc_auc,phase,branch,representation,embedding_policy,feature_type,model,test_roc_auc,test_pr_auc,test_f1,test_mcc,note,final_role
0,1,5.3,Multimodal,ProtBERT-SW + DNABERT-2,early_fusion,protein foundation embedding + genomic foundation embedding,SVM RBF,0.7568,0.7447,0.6616,0.3435,Multimodal foundation-model extension,best_roc_auc_extension_model
1,2,3.1,Multimodal,ProtBERT-SW + K3/K4/Basic,early_fusion,protein embedding + handcrafted genomic,SVM RBF,0.7290,0.7573,0.6590,0.3438,Official multimodal model before DNABERT-2,official_biologically_validated_model
2,3,3.1,Protein shared split,ProtBERT-SW,shared split,protein foundation embedding,SVM RBF,0.7274,0.7433,0.6667,0.3215,Protein-only on Phase 3 shared split,best_protein_only_shared_split_model
3,4,5.2,Genomic regulatory,DNABERT-2,sliding_window_2048_stride_1024,genomic foundation embedding,Random Forest,0.6833,0.6838,0.5478,0.2425,DNABERT-2 genomic-only extension,genomic_foundation_extension
4,5,2.1,Genomic regulatory,K3 + K4 + Basic,handcrafted,genomic handcrafted regulatory features,Random Forest,0.6496,0.6327,0.6406,0.2557,Official handcrafted genomic model,handcrafted_genomic_baseline
5,6,1.2E,Protein,ProtBERT,sliding_window_1022_stride_1022,protein foundation embedding,Logistic Regression,0.6487,0.6551,0.5896,0.1941,Best protein model before shared split,protein_foundation_baseline

,model_role,phase,model,genomic_representation,test_roc_auc,test_pr_auc,test_f1,test_mcc,top50_curated_support,top50_significant_terms,top50_t2d_relevant_terms,top_t2d_relevant_term,decision
0,Official biologically validated model,3.1,Combined ProtBERT-SW + K3/K4/Basic SVM RBF,Handcrafted K3/K4/Basic TSS-proximal regulatory features,0.7290,0.7573,0.6590,0.3438,15/50 (30.0%),102,41,Oxidative phosphorylation,Retain as main biologically validated model
1,Best ROC-AUC extension model,5.3,Combined ProtBERT-SW + DNABERT-2 SVM RBF,DNABERT-2 genomic foundation embedding,0.7568,0.7447,0.6642,0.3433,10/50 (20.0%),43,16,"DNA-binding transcription activator activity, RNA polymerase II-specific",Report as DNABERT-2 extension with best ROC-AUC

,comparison,delta_roc_auc,delta_pr_auc,delta_f1,delta_mcc,interpretation
0,Phase 5.3 DNABERT-2 extension minus Phase 3.1 handcrafted-genomic multimodal,0.0278,-0.0126,0.0052,-0.0005,"DNABERT-2 improves ROC-AUC and slightly improves F1, but the Phase 3.1 handcrafted-genomic multimodal model remains slightly better in PR-AUC and MCC."

,model,top50_curated_supported_n,top50_curated_supported_pct,top50_significant_terms,top50_t2d_relevant_terms,top_t2d_relevant_term
0,Phase 3.1 Combined ProtBERT-SW + K3/K4/Basic,15,30.0,102,41,Oxidative phosphorylation
1,Phase 5.3 Combined ProtBERT-SW + DNABERT-2,10,20.0,43,16,"DNA-binding transcription activator activity, RNA polymerase II-specific"

,claim_id,claim,evidence,support_level
0,C1,Protein foundation embeddings provide the dominant predictive signal.,"ProtBERT-SW protein-only model on shared split achieved ROC-AUC 0.7274 and PR-AUC 0.7433, close to the multimodal model.",strong
1,C2,Handcrafted TSS-proximal genomic features provide complementary signal.,"Adding K3/K4/Basic genomic features to ProtBERT-SW improved PR-AUC to 0.7573 and MCC to 0.3438, and produced the strongest biological validation results.",strong
2,C3,DNABERT-2 genomic foundation embeddings improve global ranking separation.,"Combined ProtBERT-SW + DNABERT-2 achieved the highest ROC-AUC in the project: 0.7568, improving over Phase 3.1 by +0.0278.",strong
3,C4,DNABERT-2 does not fully replace the handcrafted genomic branch in the current study.,Phase 3.1 retained higher PR-AUC and MCC and stronger top-50 biological validation than Phase 5.3.,moderate_to_strong
4,C5,The final framework is biologically plausible.,"Top true positives and top 50 Phase 3 predictions were enriched for oxidative phosphorylation, respiratory chain complex I, insulin resistance, type II diabetes mellitus, insulin secretion, and pancreas development.",strong

,section,result,key_metrics,interpretation
0,Best biologically validated model,Phase 3.1 Combined ProtBERT-SW + K3/K4/Basic SVM RBF,ROC-AUC 0.7290; PR-AUC 0.7573; F1 0.6590; MCC 0.3438,Retained as the main official model because it has the strongest biological validation.
1,Best ROC-AUC model,Phase 5.3 Combined ProtBERT-SW + DNABERT-2 SVM RBF,ROC-AUC 0.7568; PR-AUC 0.7447; F1 0.6642; MCC 0.3433,Reported as the DNABERT-2 extension and best global ranking model.
2,Biological validation,Phase 3.1 top 50 predictions,102 significant terms; 41 T2D-relevant terms; 15/50 curated support,Shows strongest enrichment and curated T2D-related support.
3,DNABERT-2 extension,Phase 5.3 top 50 predictions,43 significant terms; 16 T2D-relevant terms; 10/50 curated support,"Biologically plausible, but weaker biological validation than Phase 3.1."
4,Final conclusion,Protein embeddings dominate; genomic features complement; DNABERT-2 improves ROC-AUC.,Phase 5 ROC-AUC gain over Phase 3: +0.0278,Best framed as a biologically plausible multimodal framework with a promising genomic foundation-model extension.