In [28]:
import pandas as pd
from pathlib import Path

# Sửa tên file đúng theo file bạn đã tải
gwas_path = Path("gwas-association-downloaded_2026-05-14-MONDO_0005148.tsv")

gwas = pd.read_csv(
    gwas_path,
    sep="\t",
    low_memory=False
)

gwas.shape

(9371, 38)

In [29]:
gwas.columns.tolist()

['DATE ADDED TO CATALOG',
 'PUBMEDID',
 'FIRST AUTHOR',
 'DATE',
 'JOURNAL',
 'LINK',
 'STUDY',
 'DISEASE/TRAIT',
 'INITIAL SAMPLE SIZE',
 'REPLICATION SAMPLE SIZE',
 'REGION',
 'CHR_ID',
 'CHR_POS',
 'REPORTED GENE(S)',
 'MAPPED_GENE',
 'UPSTREAM_GENE_ID',
 'DOWNSTREAM_GENE_ID',
 'SNP_GENE_IDS',
 'UPSTREAM_GENE_DISTANCE',
 'DOWNSTREAM_GENE_DISTANCE',
 'STRONGEST SNP-RISK ALLELE',
 'SNPS',
 'MERGED',
 'SNP_ID_CURRENT',
 'CONTEXT',
 'INTERGENIC',
 'RISK ALLELE FREQUENCY',
 'P-VALUE',
 'PVALUE_MLOG',
 'P-VALUE (TEXT)',
 'OR or BETA',
 '95% CI (TEXT)',
 'PLATFORM [SNPS PASSING QC]',
 'CNV',
 'MAPPED_TRAIT',
 'MAPPED_TRAIT_URI',
 'STUDY ACCESSION',
 'GENOTYPING TECHNOLOGY']

In [30]:
gwas.head()

,DATE ADDED TO CATALOG,PUBMEDID,FIRST AUTHOR,DATE,JOURNAL,LINK,STUDY,DISEASE/TRAIT,INITIAL SAMPLE SIZE,REPLICATION SAMPLE SIZE,...,PVALUE_MLOG,P-VALUE (TEXT),OR or BETA,95% CI (TEXT),PLATFORM [SNPS PASSING QC],CNV,MAPPED_TRAIT,MAPPED_TRAIT_URI,STUDY ACCESSION,GENOTYPING TECHNOLOGY
0,2019-10-09,31513605,Jeon S,2019-09-12,PLoS One,www.ncbi.nlm.nih.gov/pubmed/31513605,Structural equation modeling for hypertension ...,Type 2 diabetes,"8,842 Korean ancestry individuals",NaN,...,5.301030,NaN,NaN,NaN,NR [327872],N,type 2 diabetes mellitus,http://purl.obolibrary.org/obo/MONDO_0005148,GCST008827,Genome-wide genotyping array
1,2012-03-10,22293688,Huang J,2012-02-01,Eur J Hum Genet,www.ncbi.nlm.nih.gov/pubmed/22293688,1000 Genomes-based imputation identifies novel...,Type 2 diabetes,"16,179 European ancestry individuals",NaN,...,7.522879,NaN,1.350000,[1.18-1.56],NR [6233112] (imputed),N,type 2 diabetes mellitus,http://purl.obolibrary.org/obo/MONDO_0005148,GCST001397,Genome-wide genotyping array
2,2020-08-22,32794382,Cho SB,2020-07-28,Diabetes Metab J,www.ncbi.nlm.nih.gov/pubmed/32794382,"Exome Chip Analysis of 14,026 Koreans Reve-als...",Type 2 diabetes,"14,026 Korean ancestry individuals",NaN,...,7.000000,NaN,1.219512,[1.14-1.32],Illumina [up to 242901],N,type 2 diabetes mellitus,http://purl.obolibrary.org/obo/MONDO_0005148,GCST010436,Exome genotyping array [Exome array]
3,2020-08-22,32794382,Cho SB,2020-07-28,Diabetes Metab J,www.ncbi.nlm.nih.gov/pubmed/32794382,"Exome Chip Analysis of 14,026 Koreans Reve-als...",Type 2 diabetes,"14,026 Korean ancestry individuals",NaN,...,6.698970,NaN,1.587302,[1.35-1.96],Illumina [up to 242901],N,type 2 diabetes mellitus,http://purl.obolibrary.org/obo/MONDO_0005148,GCST010436,Exome genotyping array [Exome array]
4,2020-08-22,32794382,Cho SB,2020-07-28,Diabetes Metab J,www.ncbi.nlm.nih.gov/pubmed/32794382,"Exome Chip Analysis of 14,026 Koreans Reve-als...",Type 2 diabetes,"14,026 Korean ancestry individuals",NaN,...,6.301030,NaN,1.204819,[1.12-1.3],Illumina [up to 242901],N,type 2 diabetes mellitus,http://purl.obolibrary.org/obo/MONDO_0005148,GCST010436,Exome genotyping array [Exome array]

In [31]:
gwas["MAPPED_TRAIT"].value_counts(dropna=False).head(20)

MAPPED_TRAIT
type 2 diabetes mellitus                                                                  8067
coronary artery calcification                                                              219
type 2 diabetes mellitus, coronary artery disorder                                         137
psoriasis, type 2 diabetes mellitus                                                         75
metabolic dysfunction-associated steatotic liver disease, type 2 diabetes mellitus          74
schizophrenia, type 2 diabetes mellitus                                                     51
prostate carcinoma, type 2 diabetes mellitus                                                43
migraine disorder, type 2 diabetes mellitus                                                 39
diabetic kidney disease, type 2 diabetes mellitus                                           39
triglyceride measurement                                                                    38
diabetic kidney disease                                                                     37
response to simvastatin, total cholesterol change measurement, response to fenofibrate      35
stroke disorder, type 2 diabetes mellitus, coronary artery disorder                         27
triglyceride change measurement, response to simvastatin, response to fenofibrate           26
diabetic kidney disease, chronic kidney disease                                             18
Headache, type 2 diabetes mellitus                                                          18
HbA1c measurement, trait in response to hypoglycemic agent                                  16
type 2 diabetes mellitus, coronary artery disorder, major depressive disorder               16
HbA1c measurement, response to sulfonylurea                                                 15
body mass index, type 2 diabetes mellitus                                                   14
Name: count, dtype: int64

In [32]:
gwas["MAPPED_TRAIT_URI"].value_counts(dropna=False).head(20)

MAPPED_TRAIT_URI
http://purl.obolibrary.org/obo/MONDO_0005148                                                                                                8067
http://www.ebi.ac.uk/efo/EFO_0004723                                                                                                         219
http://purl.obolibrary.org/obo/MONDO_0005148, http://purl.obolibrary.org/obo/MONDO_0005010                                                   137
http://purl.obolibrary.org/obo/MONDO_0005083, http://purl.obolibrary.org/obo/MONDO_0005148                                                    75
http://purl.obolibrary.org/obo/MONDO_0013209, http://purl.obolibrary.org/obo/MONDO_0005148                                                    74
http://purl.obolibrary.org/obo/MONDO_0005090, http://purl.obolibrary.org/obo/MONDO_0005148                                                    51
http://purl.obolibrary.org/obo/MONDO_0005159, http://purl.obolibrary.org/obo/MONDO_0005148                                                    43
http://purl.obolibrary.org/obo/MONDO_0005277, http://purl.obolibrary.org/obo/MONDO_0005148                                                    39
http://purl.obolibrary.org/obo/MONDO_0005016, http://purl.obolibrary.org/obo/MONDO_0005148                                                    39
http://www.ebi.ac.uk/efo/EFO_0004530                                                                                                          38
http://purl.obolibrary.org/obo/MONDO_0005016                                                                                                  37
http://purl.obolibrary.org/obo/GO_1903491, http://www.ebi.ac.uk/efo/EFO_0007806, http://purl.obolibrary.org/obo/GO_1901557                    35
http://purl.obolibrary.org/obo/MONDO_0005098, http://purl.obolibrary.org/obo/MONDO_0005148, http://purl.obolibrary.org/obo/MONDO_0005010      27
http://www.ebi.ac.uk/efo/EFO_0007681, http://purl.obolibrary.org/obo/GO_1903491, http://purl.obolibrary.org/obo/GO_1901557                    26
http://purl.obolibrary.org/obo/MONDO_0005016, http://purl.obolibrary.org/obo/MONDO_0005300                                                    18
http://purl.obolibrary.org/obo/HP_0002315, http://purl.obolibrary.org/obo/MONDO_0005148                                                       18
http://www.ebi.ac.uk/efo/EFO_0004541, http://purl.obolibrary.org/obo/OBA_2050352                                                              16
http://purl.obolibrary.org/obo/MONDO_0005148, http://purl.obolibrary.org/obo/MONDO_0005010, http://purl.obolibrary.org/obo/MONDO_0002009      16
http://www.ebi.ac.uk/efo/EFO_0004541, http://www.ebi.ac.uk/efo/EFO_0007922                                                                    15
http://www.ebi.ac.uk/efo/EFO_0004340, http://purl.obolibrary.org/obo/MONDO_0005148                                                            14
Name: count, dtype: int64

In [33]:
cols_check = [
    "SNPS",
    "SNP_ID_CURRENT",
    "STRONGEST SNP-RISK ALLELE",
    "REPORTED GENE(S)",
    "MAPPED_GENE",
    "P-VALUE",
    "PVALUE_MLOG",
    "OR or BETA",
]

pd.DataFrame({
    "column": cols_check,
    "missing_count": [gwas[c].isna().sum() for c in cols_check],
    "missing_pct": [gwas[c].isna().mean() * 100 for c in cols_check],
})

                      column  missing_count  missing_pct
0                       SNPS              0     0.000000
1             SNP_ID_CURRENT            723     7.715292
2  STRONGEST SNP-RISK ALLELE              0     0.000000
3           REPORTED GENE(S)           5302    56.578807
4                MAPPED_GENE            702     7.491196
5                    P-VALUE              0     0.000000
6                PVALUE_MLOG              0     0.000000
7                 OR or BETA           2134    22.772383

In [34]:
mapped_gene_series = (
    gwas["MAPPED_GENE"]
    .dropna()
    .astype(str)
    .str.split(",")
    .explode()
    .str.strip()
)

mapped_gene_series = mapped_gene_series[
    mapped_gene_series.ne("")
]

mapped_gene_series.nunique(), mapped_gene_series.head(20).tolist()

(3129,
 ['RN7SKP188 - ANXA10',
  'CDKN2B-AS1',
  'MARCHF3',
  'TCN2',
  'KCNQ1',
  'TCF7L2',
  'CCND2-AS1',
  'CCND2',
  'UBE2Z',
  'TCF7L2',
  'FTO',
  'CDKN2B-AS1',
  'IGF2BP2',
  'CDKAL1',
  'HHEX - Y_RNA',
  'RPSAP52',
  'RPSAP52',
  'C5orf67',
  'SLC30A8',
  'KCNQ1'])

In [35]:
reported_gene_series = (
    gwas["REPORTED GENE(S)"]
    .dropna()
    .astype(str)
    .str.split(",")
    .explode()
    .str.strip()
)

reported_gene_series = reported_gene_series[
    reported_gene_series.ne("")
]

reported_gene_series.nunique(), reported_gene_series.head(20).tolist()

(1146,
 ['intergenic',
  'CDKN2B',
  'MARCH3',
  'TCN2',
  'KCNQ1',
  'TCF7L2',
  'FTO',
  'CDKN2A',
  'CDKN2B',
  'IGF2BP2',
  'CDKAL1',
  'HHEX-IDE',
  'HMGA2',
  'ANKRD55',
  'SLC30A8',
  'KCNQ1',
  'JAZF1',
  'ARAP1',
  'CDC123',
  'CAMK1D'])

In [36]:
mapped_gene_counts = (
    mapped_gene_series
    .value_counts()
    .reset_index()
)

mapped_gene_counts.columns = [
    "mapped_gene",
    "n_gwas_association_mentions"
]

mapped_gene_counts.head(30)

           mapped_gene  n_gwas_association_mentions
0               TCF7L2                          149
1                KCNQ1                          135
2           CDKN2B-AS1                          100
3               CDKAL1                           92
4              IGF2BP2                           67
5              SLC30A8                           65
6                  FTO                           54
7      NYAP2 - MIR5702                           51
8              C5orf67                           48
9                PPARG                           44
10               HNF1B                           42
11               HNF4A                           42
12               JAZF1                           42
13        HHEX - Y_RNA                           41
14               ADCY5                           40
15  CDC123 - RN7SL198P                           39
16              UBE2E2                           39
17               GPSM1                           38
18               PDE8B                           36
19               GLIS3                           36
20               ARAP1                           34
21           LINC01080                           33
22                ANKH                           32
23           CCND2-AS1                           32
24               ZMIZ1                           32
25               RREB1                           31
26           PROX1-AS1                           31
27             RPSAP52                           30
28               CCND2                           30
29                GCKR                           29

In [37]:
reported_gene_counts = (
    reported_gene_series
    .value_counts()
    .reset_index()
)

reported_gene_counts.columns = [
    "reported_gene",
    "n_gwas_association_mentions"
]

reported_gene_counts.head(30)

   reported_gene  n_gwas_association_mentions
0             NR                         1524
1     intergenic                          165
2         TCF7L2                           69
3          KCNQ1                           51
4        IGF2BP2                           38
5         CDKAL1                           37
6        SLC30A8                           35
7           HHEX                           27
8          PPARG                           26
9         CDKN2A                           25
10        CDKN2B                           25
11           FTO                           24
12        KCNJ11                           23
13         HNF1A                           23
14          WFS1                           20
15        CDC123                           19
16         JAZF1                           17
17         HNF4A                           16
18          DGKB                           16
19         ADCY5                           16
20         RREB1                           15
21         GLIS3                           15
22          GIPR                           15
23         HNF1B                           15
24         THADA                           15
25         GRB14                           15
26          GCKR                           14
27        MTNR1B                           14
28        KLHDC5                           14
29         ZMIZ1                           14

In [38]:
gwas["P-VALUE"].describe()

count    9.371000e+03
mean     5.131586e-07
std      1.644854e-06
min      0.000000e+00
25%      2.000000e-15
50%      2.000000e-10
75%      2.000000e-08
max      1.000000e-05
Name: P-VALUE, dtype: float64

In [39]:
gwas["PVALUE_MLOG"].describe()

count    9371.000000
mean       15.487437
std        28.027094
min         5.000000
25%         7.698970
50%         9.698970
75%        14.698970
max      1314.522879
Name: PVALUE_MLOG, dtype: float64

In [40]:
gwas[
    [
        "SNPS",
        "MAPPED_GENE",
        "REPORTED GENE(S)",
        "P-VALUE",
        "PVALUE_MLOG",
        "OR or BETA",
        "STUDY ACCESSION",
        "PUBMEDID"
    ]
].sort_values(
    "PVALUE_MLOG",
    ascending=False
).head(30)

,SNPS,MAPPED_GENE,REPORTED GENE(S),P-VALUE,PVALUE_MLOG,OR or BETA,STUDY ACCESSION,PUBMEDID
8870,rs7903146,TCF7L2,NaN,0.000000e+00,1314.522879,NaN,GCST90492734,38374256
3204,rs7903146,TCF7L2,NR,0.000000e+00,694.522879,0.2800,GCST010555,32541925
2608,rs35011184,TCF7L2,NR,0.000000e+00,542.698970,0.2508,GCST010557,32541925
2060,rs34872471,TCF7L2,NaN,0.000000e+00,527.522879,0.2918,GCST90693212,38685053
4429,rs7903146,TCF7L2,NaN,0.000000e+00,525.221849,0.4027,GCST90444202,39379762
9171,rs2237897,KCNQ1,NaN,0.000000e+00,484.522879,NaN,GCST90492734,38374256
7428,rs7903146,TCF7L2,NaN,0.000000e+00,470.045757,1.3300,GCST90132183,35551307
5973,rs7903146,TCF7L2,TCF7L2,0.000000e+00,446.221849,1.3700,GCST009379,30297969
8503,rs7766070,CDKAL1,NaN,0.000000e+00,415.522879,NaN,GCST90492734,38374256
9150,rs10811661,CDKN2B-AS1,NaN,0.000000e+00,355.096910,NaN,GCST90492734,38374256
1106,rs7903146,TCF7L2,TCF7L2,0.000000e+00,347.000000,0.3059,GCST006867,30054458
6211,chr10:114749734,NaN,NaN,9.881313e-324,323.000000,0.2301,GCST90475667,39024449
6510,rs34872471,TCF7L2,NaN,9.881313e-324,323.000000,0.2316,GCST90479885,39024449
8768,rs1558902,FTO,NaN,2.000000e-309,308.698970,NaN,GCST90492734,38374256
1225,rs13214872,RPL3P2 - WASF5P,NR,2.000000e-302,301.698970,1.6700,GCST011991,33385400
1242,rs10484554,LINC02571 - HLA-B,NR,2.000000e-302,301.698970,1.6700,GCST011990,33385400
1566,rs2891168,CDKN2B-AS1,NaN,1.000000e-300,300.000000,NaN,GCST90451698,38062574
8349,rs9808924,IGF2BP2,NaN,2.000000e-279,278.698970,NaN,GCST90492734,38374256
7026,chr10:112998590,NaN,NaN,1.000000e-278,278.000000,0.2765,GCST90667974,40770095
5319,rs2237897,KCNQ1,KCNQ1,2.000000e-245,244.698970,1.2800,GCST010118,32499647
8849,rs76895963,"CCND2-AS1, CCND2",NaN,5.000000e-236,235.301030,NaN,GCST90492734,38374256
3991,rs34872471,TCF7L2,NaN,1.000000e-234,234.000000,0.2972,GCST90018926,34594039
2686,rs2237897,KCNQ1,NR,2.000000e-226,225.698970,0.2199,GCST010557,32541925
8822,rs1977833,HHEX - Y_RNA,NaN,3.000000e-223,222.522879,NaN,GCST90492734,38374256
5677,rs7903146,TCF7L2,TCF7L2,1.000000e-219,219.000000,0.3010,GCST004894,28869590
8634,rs13266634,SLC30A8,NaN,2.000000e-219,218.698970,NaN,GCST90492734,38374256
1526,rs35519679,TCF7L2,NaN,2.000000e-218,217.698970,NaN,GCST90451699,38062574
2687,rs10440833,CDKAL1,NR,5.000000e-215,214.301030,0.1286,GCST010557,32541925
6173,rs1421085,FTO,NaN,4.000000e-211,210.397940,0.1160,GCST90475667,39024449
2688,rs10811661,CDKN2B-AS1,NR,1.000000e-205,205.000000,0.1471,GCST010557,32541925

In [41]:
df_clean = pd.read_csv(r"D:\khoane\MAHE\Project\dataset\opentargets\opentargets_t2d_output\opentargets_t2d_associated_targets_clean_by_target_id.csv")

In [42]:
ot_030 = df_clean[
    df_clean["association_score"] >= 0.30
]["target_symbol"].dropna().astype(str)

mapped_genes = set(mapped_gene_series)
reported_genes = set(reported_gene_series)
ot_030_genes = set(ot_030)

{
    "mapped_gwas_genes": len(mapped_genes),
    "reported_gwas_genes": len(reported_genes),
    "ot_score_ge_030": len(ot_030_genes),
    "overlap_mapped_with_ot030": len(mapped_genes & ot_030_genes),
    "overlap_reported_with_ot030": len(reported_genes & ot_030_genes),
}

{'mapped_gwas_genes': 3129,
 'reported_gwas_genes': 1146,
 'ot_score_ge_030': 911,
 'overlap_mapped_with_ot030': 591,
 'overlap_reported_with_ot030': 336}

In [43]:
T2D_URI = "http://purl.obolibrary.org/obo/MONDO_0005148"

gwas["trait_uri_clean"] = gwas["MAPPED_TRAIT_URI"].fillna("").astype(str)

gwas_strict_t2d = gwas[
    gwas["trait_uri_clean"].str.strip() == T2D_URI
].copy()

gwas_contains_t2d = gwas[
    gwas["trait_uri_clean"].str.contains(T2D_URI, regex=False)
].copy()

gwas_non_t2d = gwas[
    ~gwas["trait_uri_clean"].str.contains(T2D_URI, regex=False)
].copy()

print("Raw file rows:", len(gwas))
print("Strict T2D only:", len(gwas_strict_t2d))
print("Contains T2D, including composite traits:", len(gwas_contains_t2d))
print("No T2D URI:", len(gwas_non_t2d))

Raw file rows: 9371
Strict T2D only: 8067
Contains T2D, including composite traits: 8830
No T2D URI: 541

In [44]:
import re
import pandas as pd

def split_mapped_genes(value):
    if pd.isna(value):
        return []
    
    value = str(value).strip()
    if not value:
        return []
    
    # Split by comma OR spaced hyphen separator used for intergenic upstream/downstream genes
    parts = re.split(r"\s*,\s*|\s+-\s+", value)
    
    return [p.strip() for p in parts if p.strip()]

mapped_gene_clean_series = (
    gwas_strict_t2d["MAPPED_GENE"]
    .dropna()
    .apply(split_mapped_genes)
    .explode()
    .dropna()
    .astype(str)
    .str.strip()
)

mapped_gene_clean_series = mapped_gene_clean_series[
    mapped_gene_clean_series.ne("")
]

print("Unique clean mapped genes:", mapped_gene_clean_series.nunique())
mapped_gene_clean_series.head(30).tolist()

Unique clean mapped genes: 2875

['RN7SKP188',
 'ANXA10',
 'CDKN2B-AS1',
 'MARCHF3',
 'TCN2',
 'KCNQ1',
 'TCF7L2',
 'CCND2-AS1',
 'CCND2',
 'UBE2Z',
 'TCF7L2',
 'FTO',
 'CDKN2B-AS1',
 'IGF2BP2',
 'CDKAL1',
 'HHEX',
 'Y_RNA',
 'RPSAP52',
 'RPSAP52',
 'C5orf67',
 'SLC30A8',
 'KCNQ1',
 'JAZF1',
 'ARAP1',
 'CDC123',
 'RN7SL198P',
 'SRBD1',
 'LINC01877',
 'FTCDNL1',
 'RPL21P41']

In [45]:
reported_gene_clean_series = (
    gwas_strict_t2d["REPORTED GENE(S)"]
    .dropna()
    .astype(str)
    .str.split(",")
    .explode()
    .str.strip()
)

reported_gene_clean_series = reported_gene_clean_series[
    ~reported_gene_clean_series.isin(["", "NR", "intergenic"])
]

print("Unique clean reported gene entries:", reported_gene_clean_series.nunique())
reported_gene_clean_series.head(30).tolist()

Unique clean reported gene entries: 893

['CDKN2B',
 'MARCH3',
 'TCN2',
 'KCNQ1',
 'TCF7L2',
 'FTO',
 'CDKN2A',
 'CDKN2B',
 'IGF2BP2',
 'CDKAL1',
 'HHEX-IDE',
 'HMGA2',
 'ANKRD55',
 'SLC30A8',
 'KCNQ1',
 'JAZF1',
 'ARAP1',
 'CDC123',
 'CAMK1D',
 'SRBD1',
 'TYW5',
 'SATB2',
 'LRIG1',
 'KBTBD8',
 'IGF2BP2',
 'BCL6',
 'LPP',
 'SOCS5P5',
 'MARCKS',
 'MTHFD1L']

In [46]:
T2D_URI = "http://purl.obolibrary.org/obo/MONDO_0005148"

gwas_strict_t2d = gwas[
    gwas["MAPPED_TRAIT_URI"].fillna("").astype(str).str.strip() == T2D_URI
].copy()

gwas_strict_t2d.shape

(8067, 39)

In [47]:
ot_030_genes = set(
    df_clean.loc[
        df_clean["association_score"] >= 0.30,
        "target_symbol"
    ]
    .dropna()
    .astype(str)
)

clean_mapped_genes = set(mapped_gene_clean_series)

{
    "strict_t2d_rows": len(gwas_strict_t2d),
    "clean_mapped_gwas_genes": len(clean_mapped_genes),
    "ot_score_ge_030": len(ot_030_genes),
    "overlap_mapped_with_ot030": len(clean_mapped_genes & ot_030_genes),
    "overlap_pct_of_ot030": len(clean_mapped_genes & ot_030_genes) / len(ot_030_genes) * 100,
}

{'strict_t2d_rows': 8067,
 'clean_mapped_gwas_genes': 2875,
 'ot_score_ge_030': 911,
 'overlap_mapped_with_ot030': 628,
 'overlap_pct_of_ot030': 68.93523600439077}

In [48]:
strict_summary = {
    "strict_t2d_association_rows": len(gwas_strict_t2d),
    "unique_studies": gwas_strict_t2d["STUDY ACCESSION"].nunique(),
    "unique_pubmed_ids": gwas_strict_t2d["PUBMEDID"].nunique(),
    "unique_snps": gwas_strict_t2d["SNPS"].nunique(),
    "unique_regions": gwas_strict_t2d["REGION"].nunique(),
    "clean_mapped_genes": mapped_gene_clean_series.nunique(),
    "clean_reported_gene_entries": reported_gene_clean_series.nunique(),
}

strict_summary

{'strict_t2d_association_rows': 8067,
 'unique_studies': 152,
 'unique_pubmed_ids': 104,
 'unique_snps': 5254,
 'unique_regions': 652,
 'clean_mapped_genes': 2875,
 'clean_reported_gene_entries': 893}

In [49]:
cols_check = [
    "SNPS",
    "SNP_ID_CURRENT",
    "STRONGEST SNP-RISK ALLELE",
    "REPORTED GENE(S)",
    "MAPPED_GENE",
    "P-VALUE",
    "PVALUE_MLOG",
    "OR or BETA",
]

strict_missingness = pd.DataFrame({
    "column": cols_check,
    "missing_count": [gwas_strict_t2d[c].isna().sum() for c in cols_check],
    "missing_pct": [gwas_strict_t2d[c].isna().mean() * 100 for c in cols_check],
})

strict_missingness

                      column  missing_count  missing_pct
0                       SNPS              0     0.000000
1             SNP_ID_CURRENT            679     8.417008
2  STRONGEST SNP-RISK ALLELE              0     0.000000
3           REPORTED GENE(S)           4657    57.729019
4                MAPPED_GENE            656     8.131895
5                    P-VALUE              0     0.000000
6                PVALUE_MLOG              0     0.000000
7                 OR or BETA           1585    19.647948

In [51]:
mapped_gene_clean_counts = (
    mapped_gene_clean_series
    .value_counts()
    .reset_index()
)

mapped_gene_clean_counts.columns = [
    "mapped_gene",
    "n_strict_t2d_gwas_mentions"
]

mapped_gene_clean_counts.head(30)

   mapped_gene  n_strict_t2d_gwas_mentions
0       TCF7L2                         135
1        KCNQ1                         132
2        Y_RNA                         101
3   CDKN2B-AS1                          92
4       CDKAL1                          88
5      SLC30A8                          70
6      IGF2BP2                          66
7          FTO                          48
8        HNF1B                          46
9        PPARG                          45
10     C5orf67                          44
11        HHEX                          43
12      CDC123                          42
13       HNF4A                          41
14   CCND2-AS1                          39
15       ADCY5                          39
16      UBE2E2                          38
17       JAZF1                          38
18   RN7SL198P                          37
19       GPSM1                          36
20       PDE8B                          36
21     MIR5702                          35
22       NYAP2                          35
23      COBLL1                          35
24        WFS1                          35
25       GLIS3                          34
26       RREB1                          34
27   LINC01080                          33
28      HMG20A                          32
29        ANK1                          32

In [50]:
thresholds = [0.10, 0.20, 0.30, 0.50]

mapped_gene_set = set(mapped_gene_clean_series)

overlap_ot_gwas_by_threshold = []

for t in thresholds:
    ot_genes_t = set(
        df_clean.loc[
            df_clean["association_score"] >= t,
            "target_symbol"
        ]
        .dropna()
        .astype(str)
    )
    
    overlap_n = len(ot_genes_t & mapped_gene_set)
    
    overlap_ot_gwas_by_threshold.append({
        "ot_score_threshold": t,
        "n_open_targets": len(ot_genes_t),
        "overlap_with_gwas_mapped_genes": overlap_n,
        "overlap_pct_of_open_targets": overlap_n / len(ot_genes_t) * 100
    })

pd.DataFrame(overlap_ot_gwas_by_threshold)

,ot_score_threshold,n_open_targets,overlap_with_gwas_mapped_genes,overlap_pct_of_open_targets
0,0.1,2123,1100,51.813472
1,0.2,1479,898,60.716700
2,0.3,911,628,68.935236
3,0.5,189,120,63.492063

In [52]:
import pandas as pd
import re

def split_mapped_genes(value):
    if pd.isna(value):
        return []
    
    value = str(value).strip()
    if not value:
        return []
    
    parts = re.split(r"\s*,\s*|\s+-\s+", value)
    return [p.strip() for p in parts if p.strip()]

gwas_mapped_expanded = gwas_strict_t2d.copy()

gwas_mapped_expanded["mapped_gene_clean"] = (
    gwas_mapped_expanded["MAPPED_GENE"]
    .apply(split_mapped_genes)
)

gwas_mapped_expanded = (
    gwas_mapped_expanded
    .explode("mapped_gene_clean")
    .dropna(subset=["mapped_gene_clean"])
)

gwas_mapped_expanded["mapped_gene_clean"] = (
    gwas_mapped_expanded["mapped_gene_clean"]
    .astype(str)
    .str.strip()
)

gwas_mapped_expanded = gwas_mapped_expanded[
    gwas_mapped_expanded["mapped_gene_clean"] != ""
].copy()

gwas_mapped_expanded.shape

(10107, 40)

In [53]:
gwas_mapped_expanded.head()

,DATE ADDED TO CATALOG,PUBMEDID,FIRST AUTHOR,DATE,JOURNAL,LINK,STUDY,DISEASE/TRAIT,INITIAL SAMPLE SIZE,REPLICATION SAMPLE SIZE,...,OR or BETA,95% CI (TEXT),PLATFORM [SNPS PASSING QC],CNV,MAPPED_TRAIT,MAPPED_TRAIT_URI,STUDY ACCESSION,GENOTYPING TECHNOLOGY,trait_uri_clean,mapped_gene_clean
0,2019-10-09,31513605,Jeon S,2019-09-12,PLoS One,www.ncbi.nlm.nih.gov/pubmed/31513605,Structural equation modeling for hypertension ...,Type 2 diabetes,"8,842 Korean ancestry individuals",NaN,...,NaN,NaN,NR [327872],N,type 2 diabetes mellitus,http://purl.obolibrary.org/obo/MONDO_0005148,GCST008827,Genome-wide genotyping array,http://purl.obolibrary.org/obo/MONDO_0005148,RN7SKP188
0,2019-10-09,31513605,Jeon S,2019-09-12,PLoS One,www.ncbi.nlm.nih.gov/pubmed/31513605,Structural equation modeling for hypertension ...,Type 2 diabetes,"8,842 Korean ancestry individuals",NaN,...,NaN,NaN,NR [327872],N,type 2 diabetes mellitus,http://purl.obolibrary.org/obo/MONDO_0005148,GCST008827,Genome-wide genotyping array,http://purl.obolibrary.org/obo/MONDO_0005148,ANXA10
1,2012-03-10,22293688,Huang J,2012-02-01,Eur J Hum Genet,www.ncbi.nlm.nih.gov/pubmed/22293688,1000 Genomes-based imputation identifies novel...,Type 2 diabetes,"16,179 European ancestry individuals",NaN,...,1.350000,[1.18-1.56],NR [6233112] (imputed),N,type 2 diabetes mellitus,http://purl.obolibrary.org/obo/MONDO_0005148,GCST001397,Genome-wide genotyping array,http://purl.obolibrary.org/obo/MONDO_0005148,CDKN2B-AS1
2,2020-08-22,32794382,Cho SB,2020-07-28,Diabetes Metab J,www.ncbi.nlm.nih.gov/pubmed/32794382,"Exome Chip Analysis of 14,026 Koreans Reve-als...",Type 2 diabetes,"14,026 Korean ancestry individuals",NaN,...,1.219512,[1.14-1.32],Illumina [up to 242901],N,type 2 diabetes mellitus,http://purl.obolibrary.org/obo/MONDO_0005148,GCST010436,Exome genotyping array [Exome array],http://purl.obolibrary.org/obo/MONDO_0005148,MARCHF3
3,2020-08-22,32794382,Cho SB,2020-07-28,Diabetes Metab J,www.ncbi.nlm.nih.gov/pubmed/32794382,"Exome Chip Analysis of 14,026 Koreans Reve-als...",Type 2 diabetes,"14,026 Korean ancestry individuals",NaN,...,1.587302,[1.35-1.96],Illumina [up to 242901],N,type 2 diabetes mellitus,http://purl.obolibrary.org/obo/MONDO_0005148,GCST010436,Exome genotyping array [Exome array],http://purl.obolibrary.org/obo/MONDO_0005148,TCN2

In [54]:
def split_reported_genes(value):
    if pd.isna(value):
        return []
    
    value = str(value).strip()
    if not value:
        return []
    
    parts = re.split(r"\s*,\s*", value)
    
    bad_values = {"", "NR", "intergenic"}
    return [p.strip() for p in parts if p.strip() not in bad_values]

gwas_reported_expanded = gwas_strict_t2d.copy()

gwas_reported_expanded["reported_gene_clean"] = (
    gwas_reported_expanded["REPORTED GENE(S)"]
    .apply(split_reported_genes)
)

gwas_reported_expanded = (
    gwas_reported_expanded
    .explode("reported_gene_clean")
    .dropna(subset=["reported_gene_clean"])
)

reported_gene_counts_for_join = (
    gwas_reported_expanded
    .groupby("reported_gene_clean")
    .size()
    .reset_index(name="gwas_reported_gene_mentions")
)

reported_gene_counts_for_join.head()

  reported_gene_clean  gwas_reported_gene_mentions
0                 A13                            1
1               ABCA1                            1
2              ABCB10                            3
3               ABCB9                            2
4               ABCC1                            1

In [55]:
gwas_gene_agg = (
    gwas_mapped_expanded
    .groupby("mapped_gene_clean")
    .agg(
        gwas_n_association_mentions=("mapped_gene_clean", "size"),
        gwas_n_unique_snps=("SNPS", "nunique"),
        gwas_n_unique_studies=("STUDY ACCESSION", "nunique"),
        gwas_n_unique_pubmed_ids=("PUBMEDID", "nunique"),
        gwas_n_unique_regions=("REGION", "nunique"),
        gwas_max_pvalue_mlog=("PVALUE_MLOG", "max"),
    )
    .reset_index()
)

gwas_gene_agg = gwas_gene_agg.merge(
    reported_gene_counts_for_join,
    left_on="mapped_gene_clean",
    right_on="reported_gene_clean",
    how="left"
)

gwas_gene_agg["gwas_has_reported_gene_support"] = (
    gwas_gene_agg["gwas_reported_gene_mentions"]
    .notna()
    .astype(int)
)

gwas_gene_agg["gwas_reported_gene_mentions"] = (
    gwas_gene_agg["gwas_reported_gene_mentions"]
    .fillna(0)
    .astype(int)
)

gwas_gene_agg = gwas_gene_agg.drop(
    columns=["reported_gene_clean"]
)

gwas_gene_agg.head()

,mapped_gene_clean,gwas_n_association_mentions,gwas_n_unique_snps,gwas_n_unique_studies,gwas_n_unique_pubmed_ids,gwas_n_unique_regions,gwas_max_pvalue_mlog,gwas_reported_gene_mentions,gwas_has_reported_gene_support
0,A1CF,1,1,1,1,1,8.000000,0,0
1,ABCA1,1,1,1,1,1,7.522879,1,1
2,ABCB10,16,1,16,11,1,43.096910,3,1
3,ABCB9,4,2,3,3,1,19.154902,2,1
4,ABCC1,1,1,1,1,1,5.154902,1,1

In [56]:
PRIMARY_POS_THRESHOLD = 0.30
HIGH_CONF_THRESHOLD = 0.50

positive_master = df_clean[
    df_clean["association_score"] >= PRIMARY_POS_THRESHOLD
].copy()

positive_master["label"] = 1
positive_master["label_name"] = "T2D_positive"
positive_master["label_source"] = "Open Targets Platform"
positive_master["label_rule"] = "OpenTargets_association_score_ge_0.30"
positive_master["label_version"] = "Positive_Label_v1"
positive_master["disease_name"] = "type 2 diabetes mellitus"
positive_master["disease_id"] = "MONDO_0005148"

positive_master["positive_tier"] = positive_master[
    "association_score"
].apply(
    lambda x: "Tier_A_high_confidence_ge_0.50"
    if x >= HIGH_CONF_THRESHOLD
    else "Tier_B_strong_positive_0.30_to_0.50"
)

In [57]:
ot_evidence_map = {
    "ds_gwas_credible_sets": "has_ot_gwas_credible_sets",
    "ds_clinical_precedence": "has_ot_clinical_precedence",
    "ds_europepmc": "has_ot_europepmc",
    "ds_gene_burden": "has_ot_gene_burden",
    "ds_eva": "has_ot_eva",
}

for score_col, flag_col in ot_evidence_map.items():
    positive_master[flag_col] = (
        positive_master[score_col].notna().astype(int)
    )

all_ds_cols = [c for c in positive_master.columns if c.startswith("ds_")]

positive_master["n_ot_evidence_datasources_present"] = (
    positive_master[all_ds_cols]
    .notna()
    .sum(axis=1)
)

In [58]:
positive_master = positive_master.merge(
    gwas_gene_agg,
    left_on="target_symbol",
    right_on="mapped_gene_clean",
    how="left"
)

positive_master["has_gwas_catalog_strict_t2d_mapping"] = (
    positive_master["mapped_gene_clean"]
    .notna()
    .astype(int)
)

positive_master = positive_master.drop(
    columns=["mapped_gene_clean"]
)

In [59]:
gwas_count_cols = [
    "gwas_n_association_mentions",
    "gwas_n_unique_snps",
    "gwas_n_unique_studies",
    "gwas_n_unique_pubmed_ids",
    "gwas_n_unique_regions",
    "gwas_reported_gene_mentions",
]

for col in gwas_count_cols:
    positive_master[col] = positive_master[col].fillna(0).astype(int)

positive_master["gwas_has_reported_gene_support"] = (
    positive_master["gwas_has_reported_gene_support"]
    .fillna(0)
    .astype(int)
)

In [60]:
positive_master.shape

(911, 58)

In [61]:
positive_master["positive_tier"].value_counts()

positive_tier
Tier_B_strong_positive_0.30_to_0.50    722
Tier_A_high_confidence_ge_0.50         189
Name: count, dtype: int64

In [62]:
positive_master["has_gwas_catalog_strict_t2d_mapping"].value_counts()

has_gwas_catalog_strict_t2d_mapping
1    628
0    283
Name: count, dtype: int64

In [63]:
positive_master.to_csv(
    "t2d_positive_labels_v1_master_with_evidence.csv",
    index=False,
    encoding="utf-8-sig"
)

In [64]:
positive_modeling = positive_master[
    [
        "target_id",
        "target_symbol",
        "target_name",
        "association_score",
        "positive_tier",
        "label",
        "label_name",
        "label_source",
        "label_rule",
        "label_version",
        "disease_id",
        "disease_name",
    ]
].copy()

positive_modeling.to_csv(
    "t2d_positive_labels_v1_modeling_minimal.csv",
    index=False,
    encoding="utf-8-sig"
)

In [65]:
prio_cols = [c for c in positive_master.columns if c.startswith("prio_")]

positive_prioritisation_metadata = positive_master[
    ["target_id", "target_symbol", "target_name"] + prio_cols
].copy()

positive_prioritisation_metadata.to_csv(
    "t2d_positive_labels_v1_target_prioritisation_metadata.csv",
    index=False,
    encoding="utf-8-sig"
)

In [6]:
import pandas as pd
df = pd.read_csv(r"D:\khoane\MAHE\Project\dataset\UniPro\category_d_genomic_sequence_output\t2d_tss_proximal_regulatory_sequences_2kbup_500bpdown_nuclear_balanced_v1.csv")
df

,gene_id,gene_symbol,gene_name,label,dataset_role,ensembl_gene_id,ensembl_gene_name,gene_type,chromosome_or_scaffold,gene_start_bp,...,tss_proximal_sequence_length,target_tss_window_length,tss_window_length_match_check,tss_sequence_orientation,left_boundary_N_padding,right_boundary_N_padding,total_N_padding,regulatory_sequence_source,regulatory_sequence_scope,regulatory_sequence_version
0,ENSG00000075643,MOCOS,MOCOS,0,negative,ENSG00000075643,MOCOS,protein_coding,18,36186894.0,...,2500,2500,True,forward_gene_orientation,0,0,0,Ensembl Homo sapiens GRCh38 primary assembly F...,TSS-proximal window: 2000 bp upstream + 500 bp...,TSS_Proximal_2kbUp_500bpDown_NuclearBalanced_v1
1,ENSG00000149596,JPH2,junctophilin 2,1,positive,ENSG00000149596,JPH2,protein_coding,20,44106590.0,...,2500,2500,True,reverse_complement_gene_orientation,0,0,0,Ensembl Homo sapiens GRCh38 primary assembly F...,TSS-proximal window: 2000 bp upstream + 500 bp...,TSS_Proximal_2kbUp_500bpDown_NuclearBalanced_v1
2,ENSG00000189043,COXFA4,cytochrome c oxidase associated subunit FA4,1,positive,ENSG00000189043,NDUFA4,protein_coding,7,10931943.0,...,2500,2500,True,reverse_complement_gene_orientation,0,0,0,Ensembl Homo sapiens GRCh38 primary assembly F...,TSS-proximal window: 2000 bp upstream + 500 bp...,TSS_Proximal_2kbUp_500bpDown_NuclearBalanced_v1
3,ENSG00000087269,NOP14,NOP14,0,negative,ENSG00000087269,NOP14,protein_coding,4,2937933.0,...,2500,2500,True,reverse_complement_gene_orientation,0,0,0,Ensembl Homo sapiens GRCh38 primary assembly F...,TSS-proximal window: 2000 bp upstream + 500 bp...,TSS_Proximal_2kbUp_500bpDown_NuclearBalanced_v1
4,ENSG00000140983,RHOT2,RHOT2,0,negative,ENSG00000140983,RHOT2,protein_coding,16,668100.0,...,2500,2500,True,forward_gene_orientation,0,0,0,Ensembl Homo sapiens GRCh38 primary assembly F...,TSS-proximal window: 2000 bp upstream + 500 bp...,TSS_Proximal_2kbUp_500bpDown_NuclearBalanced_v1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1801,ENSG00000125975,C20orf173,C20orf173,0,negative,ENSG00000125975,C20orf173,protein_coding,20,35523186.0,...,2500,2500,True,reverse_complement_gene_orientation,0,0,0,Ensembl Homo sapiens GRCh38 primary assembly F...,TSS-proximal window: 2000 bp upstream + 500 bp...,TSS_Proximal_2kbUp_500bpDown_NuclearBalanced_v1
1802,ENSG00000132972,RNF17,RNF17,0,negative,ENSG00000132972,RNF17,protein_coding,13,24764169.0,...,2500,2500,True,forward_gene_orientation,0,0,0,Ensembl Homo sapiens GRCh38 primary assembly F...,TSS-proximal window: 2000 bp upstream + 500 bp...,TSS_Proximal_2kbUp_500bpDown_NuclearBalanced_v1
1803,ENSG00000012504,NR1H4,nuclear receptor subfamily 1 group H member 4,1,positive,ENSG00000012504,NR1H4,protein_coding,12,100473708.0,...,2500,2500,True,forward_gene_orientation,0,0,0,Ensembl Homo sapiens GRCh38 primary assembly F...,TSS-proximal window: 2000 bp upstream + 500 bp...,TSS_Proximal_2kbUp_500bpDown_NuclearBalanced_v1
1804,ENSG00000063169,BICRA,BICRA,0,negative,ENSG00000063169,BICRA,protein_coding,19,47608196.0,...,2500,2500,True,forward_gene_orientation,0,0,0,Ensembl Homo sapiens GRCh38 primary assembly F...,TSS-proximal window: 2000 bp upstream + 500 bp...,TSS_Proximal_2kbUp_500bpDown_NuclearBalanced_v1
1805,ENSG00000134138,MEIS2,MEIS2,0,negative,ENSG00000134138,MEIS2,protein_coding,15,36889204.0,...,2500,2500,True,reverse_complement_gene_orientation,0,0,0,Ensembl Homo sapiens GRCh38 primary assembly F...,TSS-proximal window: 2000 bp upstream + 500 bp...,TSS_Proximal_2kbUp_500bpDown_NuclearBalanced_v1

In [7]:
df = pd.read_csv(r"D:\khoane\MAHE\Project\dataset\UniPro\category_b_outputs\t2d_protein_classification_dataset_balanced_primary_only_v1.csv")
df

,gene_id,gene_symbol,gene_name,uniprot_accession,uniprot_entry_name,sequence,sequence_length_fasta,label,label_name,dataset_role,...,uniprot_to_ensg_status,representative_sequence_rule,length_bin,ensembl_gene_id,ensembl_gene_name,gene_type,chromosome_or_scaffold,gene_start_bp,gene_end_bp,strand
0,ENSG00000161618,ALDH16A1,ALDH16A1,Q8IZ83,A16A1_HUMAN,MAATRAGPRAREIFTSLEYGPVPESHACALAWLDTQDRCLGHYVNG...,802.0,0,T2D_negative,negative,...,one_uniprot_to_one_ensg,NaN,"(683.2, 852.6]",ENSG00000161618,ALDH16A1,protein_coding,19,49453146.0,49471052.0,1.0
1,ENSG00000224420,ADM5,ADM5,C9JUS6,ADM5_HUMAN,MTIHILILLLLLAFSAQGDLDTAARRGQHQVPQHRGHVCYLGVCRT...,153.0,0,T2D_negative,negative,...,one_uniprot_to_one_ensg,NaN,"(40.999, 210.0]",ENSG00000224420,ADM5,protein_coding,19,49688953.0,49690575.0,1.0
2,ENSG00000106113,CRHR2,corticotropin releasing hormone receptor 2,Q13324,CRFR2_HUMAN,MDAALLHSLLEANCSLALAEELLLDGWGPPLDPEGPYSYCNTTLDQ...,411.0,1,T2D_positive,positive,...,one_uniprot_to_one_ensg,single_selected_sequence,NaN,ENSG00000106113,CRHR2,protein_coding,7,30651444.0,30700129.0,-1.0
3,ENSG00000165392,WRN,WRN RecQ like helicase,Q14191,WRN_HUMAN,MSEKKLETTAQQRKCPEWMNVQNKRCAVEERKACVRKSVFEDDLPF...,1432.0,1,T2D_positive,positive,...,one_uniprot_to_one_ensg,single_selected_sequence,NaN,ENSG00000165392,WRN,protein_coding,8,31033779.0,31176138.0,1.0
4,ENSG00000131196,NFATC1,nuclear factor of activated T cells 1,O95644,NFAC1_HUMAN,MPSTSFPVPSKFPLGPAAAVFGRGETLGPAPRAGGTMKSAEEEHYG...,943.0,1,T2D_positive,positive,...,one_uniprot_to_one_ensg,single_selected_sequence,NaN,ENSG00000131196,NFATC1,protein_coding,18,79395856.0,79529325.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1815,ENSG00000140623,SEPTIN12,SEPTIN12,Q8IYM1,SEP12_HUMAN,MDPLRRSPSPCLSSQPSSPSTPPCEMLGPVGIEAVLDQLKIKAMKM...,358.0,0,T2D_negative,negative,...,one_uniprot_to_one_ensg,NaN,"(315.0, 398.0]",ENSG00000140623,SEPTIN12,protein_coding,16,4777606.0,4788398.0,-1.0
1816,ENSG00000182810,DDX28,DDX28,Q9NUL7,DDX28_HUMAN,MALTRPVRLFSLVTRLLLAPRRGLTVRSPDEPLPVVRIPVALQRQL...,540.0,0,T2D_negative,negative,...,one_uniprot_to_one_ensg,NaN,"(469.0, 561.0]",ENSG00000182810,DDX28,protein_coding,16,68020916.0,68023232.0,-1.0
1817,ENSG00000167037,SGSM1,small G protein signaling modulator 1,Q2NKQ1,SGSM1_HUMAN,MASAPAEAETRQRLLRTVKKEVKQIMEEAVTRKFVHEDSSHIISFC...,1148.0,1,T2D_positive,positive,...,one_uniprot_to_one_ensg,single_selected_sequence,NaN,ENSG00000167037,SGSM1,protein_coding,22,24806169.0,24927578.0,1.0
1818,ENSG00000022567,SLC45A4,SLC45A4,Q5BKX6,S45A4_HUMAN,MKMAPQNADPESMQVQELSVPLPDPQKAGGAEAENCETISEGSIDR...,768.0,0,T2D_negative,negative,...,one_uniprot_to_one_ensg,NaN,"(683.2, 852.6]",ENSG00000022567,SLC45A4,protein_coding,8,141207166.0,141308318.0,-1.0
1819,ENSG00000196476,C20orf96,C20orf96,Q9NUD7,CT096_HUMAN,MAHVLQKPKHSGTHSIVQEFQVPDYVPWQQSKQETKPSTLPPVQQA...,363.0,0,T2D_negative,negative,...,one_uniprot_to_one_ensg,NaN,"(315.0, 398.0]",ENSG00000196476,C20orf96,protein_coding,20,270863.0,290778.0,-1.0